
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql
  namespace: {{ Values.namespace }} # this is the namespace where the deployment will be created
  labels:
    tier: db
    project: {{ Values.namespace }}
    component: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: db
      project: {{ Values.namespace }}
      component: mysql
  template:
    metadata:
      labels:
        tier: db
        project: {{ Values.namespace }}
        component: mysql
    spec:
      containers:
      - name: mysql 
        image: gopi1998/mysql:{{ Values.Deployment.imageVersion }} #will replace with our mysql image
---
apiVersion: v1
kind: Service
metadata: 
  name: mysql
  namespace: {{ Values.namespace }}
  labels:
    tier: db
    project: {{ Values.namespace }}
    component: mysql
spec:
  selector:
    tier: db
    project: {{ Values.namespace }}
    component: mysql
  ports:
  - protocol: TCP
    port: 3306 
    targetPort: 3306 