apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    project: expense
    tier: web
    component: frontend
  namespace: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      tier: web
      component: frontend
  template:
    metadata:
      labels:
        project: expense
        tier: web
        component: frontend
    spec:
      containers:
      - name: frontend
        image: gopi1998/frontend:{{ .Values.Deployment.imageVersion }} #will replace with our frontend image
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
      volumes:
      - name: nginx-config
        configMap:
          name: frontend
          items:
          - key: nginx.conf
            path: nginx.conf

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    project: expense
    tier: web
    component: frontend
  namespace: expense
spec:
  type: LoadBalancer #this will create a load balancer service and this will only work on cloud provider
  selector:
    project: expense
    tier: web
    component: frontend
  ports:
  - port: 80 #port on which service will be exposed
    targetPort: {{ .Values.configmap.port }} #port on which pod is running