apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql #this is the service name of mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    project: expense
    tier: app
    component: backend
  namespace: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      tier: app
      component: backend
  template:
    metadata:
      labels:
        project: expense
        tier: app
        component: backend
    spec:
      containers:
      - name: backend
        image: gopi1998/backend:{{ .Values.Deployment.imageVersion }} #will replace with our backend image
        envFrom:
        - configMapRef:
            name: backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    project: expense
    tier: app
    component: backend
  namespace: expense
spec:
  selector:
    project: expense
    tier: app
    component: backend
  ports:
  - port: 8080
    targetPort: 8080
  
